### ISSUE TITLE
to_lower is not defined

### ISSUE THREAD

**Issue by ferhatguneri** [brolin59/PYTHON-TURKCE-DOGAL-DIL-ISLEME-TURKISH-NLP#1]
Hi,

I'v tried your library but I couldn't find to_lower function in SentenceTokenization.py file. Therefore library couldn't tokenize my sentence. Could you please check it?

File "C:\Users\ferhat.guneri\AppData\Local\Programs\Python\Python37-32\lib\site-packages\trnlp\Tokenization\SentenceTokenization.py", line 290, in sentence_token_wsign
    if to_lower(kisim) in shortlist:
NameError: name 'to_lower' is not defined

Regards.

**Comment by ferhatguneri** [comment]
Hi Again,
You can find corret code below for both condition.

            if str.lower(kisim) in shortlist:
                gecici.append(kisim)
                continue

            if str.lower(kisim) in shortlist:
                gecici.append('{KI}' + kisim + '{/KI}')
                continue

**Comment by bmakokha** [comment]
thanks @ferhatguneri your code was helpful to me.
