### ISSUE TITLE
kelime tipi belirlenirken isimlerde sıfat köklerine iniyor

### ISSUE THREAD

**Issue by gurkangulcan** [brolin59/PYTHON-TURKCE-DOGAL-DIL-ISLEME-TURKISH-NLP#10]
Bir text içinde kelimelerin tek tek sıfat mı isim mi olduğunu araştırırken gözlemledim.

**Smartphone (please complete the following information):**
 - Device: MAC
 - OS: MAC OS Sonoma ver 14.6.1
 - Browser Firefox
 - Version latest available

**Additional context**
"Halil" isminde karşılaştım bu durumla. Kelimeyi isim olarak görmek yerine "hali" sıfatı olarak görüyor. Temel olarak aşağıdaki kod ile denenebilir.

from trnlp import TrnlpWord

obj = TrnlpWord()
obj.setword("halil")
print(obj)

trnlp/data/ana_sozluk.txt içerisinde "halile" isim olarak bulunsa da "halil" isim olarak geçmiyor. "halil" kelimesini de elimdeki ana_sozluk.txt dosyasının içine ayrı bir satır olarak yazdım. Ancak halen "hali" kökünü gösteriyor.
isim için ayrı bir kontrol eklenebilir mi?

**Comment by brolin59** [comment]
trnlp sözlük ve ek bilgilerini pickle dosyası olarak kaydeder ve bu dosyalardan okur.  txt dosyasında düzenleme yaptığınız zaman /trnlp/generator/createLexiconsPickle.py kodunu çalıştırmanız gerekir. Kodu her hangi bir python ide programında açıp çalıştırmanız yeterlidir. .txt dosyasına doğru bir şekilde yani formata uygun bir şekilde ekleme yaptıysanız sorununuz düzelecektir. Bu konu ile ilgili aşağıdaki linkten "Sözlükler" bölümünü inceleyebilirsiniz.

[https://github.com/brolin59/trnlp/wiki](url)

**Comment by gurkangulcan** [comment]
Teşekkürler. Wiki'yi daha dikkatli okuyacağım.
