### ISSUE TITLE
Sayıların Yazıya Çevrilişi

### ISSUE THREAD

**Issue by EkremDincel** [brolin59/PYTHON-TURKCE-DOGAL-DIL-ISLEME-TURKISH-NLP#2]
Türkçe'de sayılar harflerle yazılırken kelimeler arasında boşluk bırakılır ([kaynak](http://tdk.gov.tr/icerik/yazim-kurallari/sayilarin-yazilisi/)). Şu anda `trnlp.helpers.number_to_word` bunu yapmıyor. Benim örnek bir algoritmam var:
https://gist.github.com/EkremDincel/395afb9efbd99a9509bc3a11178482d8

**Comment by brolin59** [comment]
Yeni versiyonu daha yayınlamadım. Kaynak ve örnek kod için teşekkür ederim.
